name: FUSE Tests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up system
        shell: bash
        run: |
          bash <(wget -q -O- http://neuro.debian.net/_files/neurodebian-travis.sh)
          # enable repo for devel git-annex, if needed
          #sudo sed -e 's|\(deb.*data\)|#\1|' -e 's|/debian |/debian-devel |' /etc/apt/sources.list.d/neurodebian.sources.list | sudo tee /etc/apt/sources.list.d/neurodebian-devel.sources.list
          sudo apt-get update -qq
          sudo apt-get install eatmydata
          sudo eatmydata apt-get install -y fuse git-annex-standalone

      - name: Set up environment
        run: |
          git config --global user.email "test@github.land"
          git config --global user.name "GitHub Almighty"

      - uses: actions/checkout@v2

      - name: Set up Python 3.6
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install datalad tox

      - name: Run tests
        run: |
          mkdir -p __testhome__
          cd __testhome__
          # give detailed info on actual test setup
          datalad wtf
          tox -e py3
